[theme]
primaryColor = "#1E88E5"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E2025"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[client]
toolbarMode = "auto"
showErrorDetails = true